### ISSUE TITLE
Adding new provider

### ISSUE THREAD

**Issue by codivist** [kalley/laravel-oauth-client#2]
I'm trying to add my own Stripe provider.  I'm using https://github.com/chrsm/league-oauth2-stripe for the Stripe Provider, and when I set up my StripeFacade, I get the following error:
```
Undefined index: stripe
in
/srv/www/practiscore.dev/deploy/matchReg/vendor/kalley/laravel-oauth-client/src/Kalley/LaravelOauthClient/AbstractOAuthClient.php
on
line 26
```
How do I go about adding a custom provider with the facade?

Here is my facade:
```php
<?php

namespace Practiscore\Facades;

use Illuminate\Support\Facades\Facade;

class StripeFacade extends Facade {

	/**
	 * Get the registered name of the component
	 * @return string
	 * @codeCoverageIgnore
	 */
	protected static function getFacadeAccessor() {
		return 'oauth-client.stripe';
	}

}
```
And have this in my oauth-client.php config file:
```php
'providers' => [
		'Facebook' => [...],

		'Github'   => [...],

		'Stripe' => [
			'clientId'     => 'myClientID',
			'clientSecret' => 'myClientSecret',
			'redirectUri'  => 'https://myexample.com/stripe/incoming',
		],

	],
```
Also added the alias in app.php

**Comment by geofflancaster** [comment]
I haven't tried to replicate your code but at quick glance, PHP array keys are case sensitive. I'd try to sync those up.

example:

protected static function getFacadeAccessor() {
        return 'oauth-client.Stripe';
    }


or
'providers' => [
        'facebook' => [...],

        'github'   => [...],

        'stripe' => [
            'clientId'     => 'myClientID',
            'clientSecret' => 'myClientSecret',
            'redirectUri'  => 'https://myexample.com/stripe/incoming',
        ],

    ],

**Comment by codivist** [comment]
If that were the case, then my Facebook and Github providers would not work and they are working.
The `AbstractOAuthClient.php` and `LaravelOauthClientServiceProvider.php` actually take care of converting the providers to lower case before being processed. 

I can't figure out if the `protected $mapped` array is telling this package to ONLY use whats in that array, or if there is somewhere else that is causing my stripe stuff to be ignored.

**Comment by codivist** [comment]
:bow: Thanks for fixing this.  I've been on vacation and another project so I'm jumping back into this. Looks good.  I'll let you know how it goes.
